### ISSUE TITLE
TypeError: array_merge(): Argument #1 must be of type array, null given in /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Cart/Cart.php:294

### ISSUE THREAD

**Issue by walkwizus** [hipay/hipay-fullservice-sdk-magento2#159]
Lors d'un paiement, une erreur est levée dans la classe: `hipay/hipay-fullservice-sdk-magento2/Model/Cart/Cart.php`

L'attribut de classe `$_itemsCollectingRequired` est déjà déclaré dans la classe parente et initialisé à true. Je pense qu'il n'est pas nécessaire de redéfinir cet attribut de classe et de plus sans aucune initialisation, la valeur sera à NULL.

Voici l'erreur après test d'un passage de paiement:

```
TypeError: array_merge(): Argument #1 must be of type array, null given in /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Cart/Cart.php:294
Stack trace:
#0 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Cart/Cart.php(294): array_merge(NULL, NULL)
#1 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Request/CommonRequest.php(185): HiPay\FullserviceMagento\Model\Cart\Cart->getAllItems('0')
#2 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Request/Order.php(438): HiPay\FullserviceMagento\Model\Request\CommonRequest->processCartFromOrder('Authorization', '0')
#3 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Request/Order.php(329): HiPay\FullserviceMagento\Model\Request\Order->processExtraInformations(Object(HiPay\Fullservice\Gateway\Request\Order\OrderRequest), '0')
#4 /var/www/html/generated/code/HiPay/FullserviceMagento/Model/Request/Order/Interceptor.php(23): HiPay\FullserviceMagento\Model\Request\Order->mapRequest()
#5 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Request/AbstractRequest.php(135): HiPay\FullserviceMagento\Model\Request\Order\Interceptor->mapRequest()
#6 /var/www/html/generated/code/HiPay/FullserviceMagento/Model/Request/Order/Interceptor.php(140): HiPay\FullserviceMagento\Model\Request\AbstractRequest->getRequestObject()
#7 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Gateway/Manager.php(318): HiPay\FullserviceMagento\Model\Request\Order\Interceptor->getRequestObject()
#8 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Gateway/Manager.php(214): HiPay\FullserviceMagento\Model\Gateway\Manager->_getRequestObject('\\HiPay\\Fullserv...', Array)
#9 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Method/FullserviceMethod.php(444): HiPay\FullserviceMagento\Model\Gateway\Manager->requestNewOrder()
#10 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Method/FullserviceMethod.php(362): HiPay\FullserviceMagento\Model\Method\FullserviceMethod->place(Object(Magento\Sales\Model\Order\Payment\Interceptor))
#11 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Method/CcMethod.php(158): HiPay\FullserviceMagento\Model\Method\FullserviceMethod->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), 494.8)
#12 /var/www/html/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Method/CcMethod.php(132): HiPay\FullserviceMagento\Model\Method\CcMethod->processAction('Sale', Object(Magento\Sales\Model\Order\Payment\Interceptor))
#13 /var/www/html/vendor/magento/module-sales/Model/Order/Payment.php(377): HiPay\FullserviceMagento\Model\Method\CcMethod->initialize('Sale', Object(Magento\Framework\DataObject))
#14 /var/www/html/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(122): Magento\Sales\Model\Order\Payment->place()
#15 /var/www/html/vendor/magento/module-sales/Model/Order.php(1002): Magento\Sales\Model\Order\Payment\Interceptor->place()
#16 /var/www/html/vendor/magento/module-sales/Model/Order.php(1228): Magento\Sales\Model\Order->_placePayment()
#17 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()
#18 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)
#19 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()
#20 /var/www/html/generated/code/Magento/Sales/Model/Order/Interceptor.php(356): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)
#21 /var/www/html/vendor/magento/module-sales/Model/Service/OrderService.php(207): Magento\Sales\Model\Order\Interceptor->place()
#22 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))
#23 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Service\OrderService\Interceptor->___callParent('place', Array)
#24 /var/www/html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(166): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#25 /var/www/html/vendor/magento/module-inventory-sales/Plugin/Sales/OrderManagement/AppendReservationsAfterOrderPlacementPlugin.php(141): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->createOrder(Object(Closure), Object(Magento\Sales\Model\Order\Interceptor), Array, Object(Magento\InventorySales\Model\SalesChannel), Object(Magento\InventorySalesApi\Api\Data\SalesEventExtension))
#26 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\Sales\OrderManagement\AppendReservationsAfterOrderPlacementPlugin->aroundPlace(Object(Magento\Sales\Model\Service\OrderService\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor))
#27 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Service\OrderService\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor))
#28 /var/www/html/generated/code/Magento/Sales/Model/Service/OrderService/Interceptor.php(86): Magento\Sales\Model\Service\OrderService\Interceptor->___callPlugins('place', Array, Array)
#29 /var/www/html/vendor/magento/module-quote/Model/QuoteManagement.php(624): Magento\Sales\Model\Service\OrderService\Interceptor->place(Object(Magento\Sales\Model\Order\Interceptor))
#30 /var/www/html/vendor/magento/module-quote/Model/QuoteManagement.php(500): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#31 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#32 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteManagement\Interceptor->___callParent('submit', Array)
#33 /var/www/html/vendor/magento/module-sales-rule/Plugin/CouponUsagesIncrement.php(54): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor), Array)
#34 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\SalesRule\Plugin\CouponUsagesIncrement->aroundSubmit(Object(Magento\Quote\Model\QuoteManagement\Interceptor), Object(Closure), Object(Magento\Quote\Model\Quote\Interceptor))
#35 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteManagement\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
#36 /var/www/html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(68): Magento\Quote\Model\QuoteManagement\Interceptor->___callPlugins('submit', Array, NULL)
#37 /var/www/html/vendor/magento/module-quote/Model/QuoteManagement.php(458): Magento\Quote\Model\QuoteManagement\Interceptor->submit(Object(Magento\Quote\Model\Quote\Interceptor))
#38 /var/www/html/generated/code/Magento/Quote/Model/QuoteManagement/Interceptor.php(50): Magento\Quote\Model\QuoteManagement->placeOrder(14, NULL)
#39 /var/www/html/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(152): Magento\Quote\Model\QuoteManagement\Interceptor->placeOrder(14)
#40 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(14, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#41 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)
#42 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(14, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#43 /var/www/html/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(23): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)
#44 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(14, Object(Magento\Quote\Model\Quote\Payment), Object(Magento\Quote\Model\Quote\Address\Interceptor))
#45 /var/www/html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#46 /var/www/html/vendor/magento/module-webapi/Controller/Rest.php(202): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#47 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#48 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#49 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#50 /var/www/html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#51 /var/www/html/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#52 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#53 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent('launch', Array)
#54 /var/www/html/vendor/justbetter/magento2-sentry/Plugin/GlobalExceptionCatcher.php(57): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#55 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(135): JustBetter\Sentry\Plugin\GlobalExceptionCatcher->aroundLaunch(Object(Magento\Framework\App\Http\Interceptor), Object(Closure))
#56 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#57 /var/www/html/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins('launch', Array, Array)
#58 /var/www/html/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#59 /var/www/html/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#60 {main}
```

**Comment by JBaptisteLvt** [comment]
Bonjour

L'anomalie a été relevée déjà en interne, elle sera corrigée dans la prochaine version du module.
Merci pour ce retour !

**Comment by JBaptisteLvt** [comment]
Corrigé dans la version 1.20.0 du 6 Juillet
